version: 3

tasks:
  clean:
    desc: Clean
    cmds:
      - rm -rf build

  build:
    desc: Build
    cmds:
      - go mod download
      - go mod tidy
      - go install .

  test:
    desc: Test
    deps: [ build ]
    cmds:
      - rm -rf ${OUTPUT_DIR}
      - mkdir -p ${OUTPUT_DIR}
      - protoc -I ${PB_DIR} --twirp-java_out=${OUTPUT_DIR} ${PB_DIR}/service.proto
      - protoc -I ${PB_DIR} --twirp-java_out=${OUTPUT_DIR} ${PB_DIR}/model.proto
    env:
      PB_DIR: ../protobuf
      OUTPUT_DIR: ../java/build/generated/source/protoc-gen-twirp-java/main/java

  docker-build:
    desc: Build Docker image
    cmds:
      - docker build --tag go-protoc-twirp-java:latest .

  docker-inspect:
    deps: [ docker-build ]
    cmds:
      - docker run --rm -it go-protoc-twirp-java:latest /bin/sh

  docker-test:
    deps: [ docker-build ]
    cmds:
      - mkdir -p build
      - docker run --rm -it
          --user $(id -u):$(id -g)
          -v $(pwd)/../protobuf:/protobuf 
          -v $(pwd)/build:/build
          go-protoc-twirp-java:latest 
          protoc --proto_path=/protobuf --twirp-java_out=/build service.proto
